# Generated by Django 3.1.2 on 2021-02-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabExam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labexam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('exam_name', models.CharField(max_length=200)),
                ('exam_description', models.TextField()),
                ('image_url', models.CharField(max_length=500)),
                ('total_marks', models.FloatField()),
                ('pass_marks', models.FloatField()),
                ('exam_status', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='exam_date',
        ),
    ]
