# Generated by Django 3.1.2 on 2021-02-25 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabExam', '0002_auto_20210225_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labexam',
            name='image_url',
        ),
    ]
